name: 'Docker - Build Docker Runtime'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  release-docker:
    name: Docker release
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: 'production'
          tags: opwork/runtime:${{ steps.short-sha.outputs.sha }},opwork/runtime:latest
          context: ./runtime/
